<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-4-g7f85cfe  Build Version: 1.6.7995.38578
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot name="table_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="teabox_height" value="0.20"/>
  <xacro:property name="teabox_width" value="0.11"/>
  <xacro:property name="teabox_length" value="0.075"/>    

  <xacro:property name="coffeebox_height" value="0.17"/>
  <xacro:property name="coffeebox_width" value="0.07"/>
  <xacro:property name="coffeebox_length" value="0.07"/>

  <xacro:property name="glassesbox_height" value="0.07"/>
  <xacro:property name="glassesbox_width" value="0.07"/>
  <xacro:property name="glassesbox_length" value="0.17"/>

  <xacro:property name="tennisball_radius" value="0.06"/>

  <xacro:macro name="table" params="prefix x y z theta">
    <link name="${prefix}_table_base_link"/>
    <joint name="${prefix}_table_base_joint" type="fixed">
      <origin xyz="${x} ${y} ${z}" rpy="0 0 ${theta}" />
      <parent link="world" />
      <child link="${prefix}_table_base_link" />
      <axis xyz="0 0 0" />
    </joint>

    <link name="${prefix}_table_link">
      <inertial>
        <origin xyz="0 1.66533453693773E-16 0.739609856262833" rpy="0 0 0" />
        <mass value="97.4000000000001" />
        <inertia ixx="10.6298985078713" ixy="-1.55850332639318E-14" ixz="1.61645738949227E-14" iyy="22.2248985078712" iyz="1.27560526488281E-14" izz="29.9373333333332" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://env_description/tieta_env/assets/rigid/table_link.STL" scale="0.8 0.6 0.9375" />
        </geometry>
        <material name="">
          <color rgba="0.564705882352941 0.564705882352941 0.564705882352941 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://env_description/tieta_env/assets/rigid/table_link.STL" scale="0.85 0.7 0.9375"/>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_table_joint" type="fixed">
      <origin xyz="0 0 -0.75" rpy="0 0 1.57" />
      <parent link="${prefix}_table_base_link" />
      <child link="${prefix}_table_link" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- <link name="${prefix}_table_teabox">
      <visual>
        <origin rpy="0 0 1.57" xyz="-0.4 0 ${teabox_height/2 + 0.739609856262833}"/>
        <geometry>
          <box size="${teabox_length} ${teabox_width} ${teabox_height}"/>
        </geometry>
        <material name="omni/Yellow"/>
      </visual>
      <collision>
          <origin rpy="0 0 1.57" xyz="-0.4 0 ${teabox_height/2 + 0.739609856262833}"/>
          <geometry>
            <box size="${teabox_length+0.05} ${teabox_width+0.05} ${teabox_height+0.05}" />
          </geometry>
          
      </collision>
    </link>

    <joint name="${prefix}_joint_teabox" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="${prefix}_table_link"/>
      <child link="${prefix}_table_teabox"/>
      <dynamics damping="1.0" friction="1.0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="${prefix}_table_coffeebox">
      <visual>
        <origin rpy="0 0 1.57" xyz="0.4 0 ${coffeebox_height/2 + 0.739609856262833}"/>
        <geometry>
          <box size="${coffeebox_length} ${coffeebox_width} ${coffeebox_height}"/>
        </geometry>
        <material name="omni/LightGrey"/>
      </visual>
      <collision>
          <origin rpy="0 0 1.57" xyz="0.4 0 ${coffeebox_height/2 + 0.739609856262833}"/>
          <geometry>
            <box size="${coffeebox_length+0.05} ${coffeebox_width+0.05} ${coffeebox_height+0.06}" />
          </geometry>
          
      </collision>
    </link>

    <joint name="${prefix}_joint_coffeebox" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="${prefix}_table_link"/>
      <child link="${prefix}_table_coffeebox"/>
      <dynamics damping="1.0" friction="1.0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="${prefix}_table_glassesbox">
      <visual>
        <origin rpy="0 0 1.57" xyz="0 0.15 ${glassesbox_height/2 + 0.739609856262833}"/>
        <geometry>
          <box size="${glassesbox_length} ${glassesbox_width} ${glassesbox_height}"/>
        </geometry>
        <material name="omni/Yellow"/>
      </visual>
      <collision>
          <origin rpy="0 0 1.57" xyz="0 0.15 ${glassesbox_height/2 + 0.739609856262833}"/>
          <geometry>
            <box size="${glassesbox_length+0.05} ${glassesbox_width+0.05} ${glassesbox_height+0.08}" />
          </geometry>
          
      </collision>
    </link>

    <joint name="${prefix}_joint_glassesbox" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="${prefix}_table_link"/>
      <child link="${prefix}_table_glassesbox"/>
      <dynamics damping="1.0" friction="1.0"/>
      <axis xyz="1 0 0"/>
    </joint>


    <link name="${prefix}_table_tennisball">
      <visual>
        <origin rpy="0 0 0" xyz="0.32 -0.22 ${tennisball_radius + 0.739609856262833}"/>
        <geometry>
          <sphere radius="${tennisball_radius}"/>
        </geometry>
        <material name="omni/Green"/>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0.32 -0.22 ${tennisball_radius + 0.739609856262833}"/>
          <geometry>
            <sphere radius="${tennisball_radius+0.03}"/>
          </geometry>
          
      </collision>
    </link>

    <joint name="${prefix}_joint_tennisball" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="${prefix}_table_link"/>
      <child link="${prefix}_table_tennisball"/>
      <dynamics damping="1.0" friction="1.0"/>
      <axis xyz="1 0 0"/>
    </joint> -->



    
  </xacro:macro>
</robot>